### ISSUE TITLE
Marker clusterer bug while dragging the map

### ISSUE THREAD

**Issue by sanford-opspl** [googlemaps/js-markerclustererplus#10]
Okay, I'm developing an Ionic 3 app and implemented the Google Maps along with Marker Clustering too. I noticed that when I drag the map, there is an issue. If I start dragging the map while my finger is on one of the marker clusters, the map cannot be dragged. But if I do the same outside the area, it works fine.

Am I missing something or this bug actually exists? Kindly help.

**Comment by TarasZakus** [comment]
A little dirty hack, that works for me:
```
// TODO: remove, once this [this](https://github.com/googlemaps/js-markerclustererplus/issues/10) is resolved
google.maps.version = '3.31.9';

const markerCluster = new MarkerClusterer(map, markers);
```

**Comment by Jasper992** [comment]
Hi guys, is there still no solution for this problem? 
I'm facing the same issue rn,,

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by jpoehnelt** [comment]
See #300.
