### ISSUE TITLE
Be able to update the `clickable` property clusters

### ISSUE THREAD

**Issue by Frankwarnaar** [googlemaps/js-markerclustererplus#102]
To begin, I'd like to thank you for creating this library!

 **Is your feature request related to a problem? Please describe.**
Currently (as far as I'm aware) it's not possible to make to update the `clickable` property of the marker representing a cluster (I believe this is called a `ClusterAugmentedMarker` in your codebase). I want to update the clickable behavior when the user is zoomed in to the maximum zoom level Google maps supports. Currently I can only update the `zoomOnClickUpdate` property of my clusterer, but then the `ClusterAugmentedMarker` still has `cursor: pointer`.

 **Describe the solution you'd like**
I'd like to be able to update the `clickable` property of the cluster. Maybe the `clickable` option could be added to the `MarkerClustererOptions` and the `setClickable` method could be added to the `MarkerClusterer` as well, so I can configure this when using the library.

 **Describe alternatives you've considered**
I've already been trying to update `MarkerClusterer.zoomOnClick` by `setZoomOnClick`. Now this disables the listener to zoom on click, but it still looks clickable (`cursor: pointer`). 
Also I've been researching wether I'm able to access the `ClusterAugmentedMarker` to use the `setClickable` method, but since it's a private internal of your library, I believe I'm not able to do so.

 **Additional context**
In my use case, it's possible having multiple markers on the exact same coordinates:
![Screenshot 2021-01-11 at 13 21 26](https://user-images.githubusercontent.com/14164215/104181820-b56d1680-540f-11eb-807c-d24891de7184.png)
Therefore, the user will end up in a state where he is at the deepest zoom level and the cluster still looks clickable. However, when the cluster is clicked, nothing happens.

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by jpoehnelt** [comment]
See #300.
