### ISSUE TITLE
Added second @ sign to escape the other @ sign in JS script tag in Readme.

### ISSUE THREAD

**Issue by SeppPenner** [googlemaps/js-markerclustererplus#113]
As far as I know, the `@` sign in `<script src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>` should be escaped like so:

`<script src="https://unpkg.com/@@googlemaps/markerclustererplus/dist/index.min.js"></script>`

as some editors mark it as error otherwise.

**Comment by jpoehnelt** [comment]
Can you link to a specification or similar showing this? I've never personally seen this and wonder how it will affect the NPM page for instance.

**Comment by jpoehnelt** [comment]
GitHub doesn't like it. 

![Screenshot 2021-01-29 9 18 48 AM](https://user-images.githubusercontent.com/3392975/106299930-0ef88200-6213-11eb-91c9-4dac9305960c.png)

**Comment by SeppPenner** [comment]
It affects e.g. Visual Studio's HTML viewer:

![grafik](https://user-images.githubusercontent.com/9639361/106307253-691f3480-625f-11eb-9a1b-d8595d62b02d.png)
vs.
![grafik](https://user-images.githubusercontent.com/9639361/106307299-776d5080-625f-11eb-9012-9f45b2ef181b.png)
