### ISSUE TITLE
Performance suggestion - optimize distanceBetweenPoints_

### ISSUE THREAD

**Issue by d1manson** [googlemaps/js-markerclustererplus#152]
This is a minor (but somewhat interesting) performance suggestion.

The `distanceBetweenPoints_` function probably doesn't need to provide true kms in order to do clustering, since it seems (at least in some configurations) clustering just needs to know the smallest distance over a set of distances not the absolute magnitude of that distance.

https://github.com/googlemaps/js-markerclustererplus/blob/main/src/markerclusterer.ts#L1025

In particular,  `atan2(sqrt(a), sqrt(1-a))` is monotonically increasing for `a` in `[0,1]`, which is the range of interest (if `a` is greater than 1 or less than 0 then one or other of the sqrts wouldn't give real numbers).

![Screenshot 2021-03-20 at 14 37 44](https://user-images.githubusercontent.com/4244876/111873748-d874f300-8989-11eb-8458-8f9eecea730b.png)

As such, it seems redundant to perform the (somewhat expensive) double square root and inverse tan.

For additional optimization, it seems you could precompute some of the trig values for the nucleus of each cluster rather than doing it in the  `distanceBetweenPoints_` function each time.

I understand that maybe this is overkill, but thought it was worth at least point it out.

**Comment by jpoehnelt** [comment]
See #300.
