### ISSUE TITLE
fitMapToMarkers / fitBounds break clusterers

### ISSUE THREAD

**Issue by jankowskip** [googlemaps/js-markerclustererplus#171]
I've implemented autozoom to boundries of markers, but seems like clusterer does not catch zoom change. 
Result: Clicking on cluster does not work, clusters does not render properly sometimes

**Tip**: _If you change the zoom a little bit manually, everything work as expected (clusters render properly and clicking on them works again)_ 

#### Environment details
    "@angular/cdk": "^8.2.3",
    "@googlemaps/markerclustererplus": "^1.0.3",
    "@googlemaps/markerwithlabel": "^1.0.3",
    
    // Tested on iphone 10 and macOS, didnt have chance to check it on other OS / android 

#### Steps to reproduce
  1. Render multiple markers
  2. Put them in clusterer and add to map 
  3. Implement autozoom to markers boundries
  4. Click on clusterer 

#### Code example

```
    const positions = [] // some array with random positions 
    const markers = positions.map(({ lat, lng }) => this.createMarker(lat, lng));
    this.markerClusters = new MarkerClusterer(this.map, markers, {
      minimumClusterSize: 3,
      styles: [
        {
          url: 'assets/icons/maps/cluster_marker.png',
          textColor: '#fff',
          width: 40,
          height: 40,
          textLineHeight: 40,
        },
      ],
      maxZoom: 17,
    });
    this.markerClusters.fitMapToMarkers(10); // <--- This line creates a bug
    
    
  createMarker(lat, lng) {
    const marker = new MarkerWithLabel({
      labelContent: '',
      labelAnchor: new google.maps.Point(-40, 5),
      position: { lat, lng },
    });
    return marker;
  }
```

**Additional note:** I did try to zoom directly from markers and got same result, so its not the problem with fitMapToMarkers method.

```
    const bounds = new google.maps.LatLngBounds();
    this.markers.forEach(marker => bounds.extend(marker.getPosition()));
    this.map.fitBounds(bounds);
```
Sadly this problem might be in google map js core, might be that `fitBounds` does not fire zoom change event :( 

Gif with bug:
![bug-autozoom](https://user-images.githubusercontent.com/12384594/113637133-2ff6ac80-9674-11eb-8ee6-987150ba0368.gif)

Let me know if you need anything else

Offtop: 
@jpoehnelt i told everybody in Company about your super quick issue resolving skills (you helped us a lot in MarkerWithLabel) So you have reputation to maintain :D

**Comment by jankowskip** [comment]
My guess was wrong, had some time to investigate it again, the issue is connected to panTo function

Workaround untill it gets fixed would be to wait for panTo finish and repaint clusters
```
    google.maps.event.addListenerOnce(this.map, 'idle', () => {
      this.markerClusters.repaint();
    });
```

**Comment by jpoehnelt** [comment]
See #300.
