### ISSUE TITLE
New patch release (v1.1.1)

### ISSUE THREAD

**Issue by JUX84** [googlemaps/js-markerclustererplus#177]
Hello,

As I stated in my PR https://github.com/googlemaps/js-markerclustererplus/pull/153
And was confirmed in this closed issue by someone https://github.com/googlemaps/js-markerclustererplus/issues/164

The new google maps types maintained by google is `@types/google.maps` instead of `@types/googlemaps`.
So everyone who uses the correct one now, in addition to your library, has typescript issues due to these type conflicts.

Could it be possible to create a new release so we can update our dependencies? (without having to build the newest version manually)

Sorry to create an issue just for this, but it's been impacting my CI for a few weeks now.

Also, I don't know what the impact will be for people using the old `@types/googlemaps` types with the fix made by my PR, so it should be checked wether it's ok or not to create a patch release, or if it should be a minor one.

Thank you for your time.

**Comment by jpoehnelt** [comment]
Since this was a devDependency, a new release was not made, i will look into manually do this.

**Comment by JUX84** [comment]
Hey Justin,

I was wondering if there were any ETA on this manual release.
As I stated in the OP, my CI has been stuck due to this for more than a month now.

I was just wondering if you forgot about it or if there was more to it than that 😀

Thanks o/
