### ISSUE TITLE
Maps: Markers do not load on google map

### ISSUE THREAD

**Issue by ltoshev** [googlemaps/js-markerclustererplus#215]
#### Environment details

2. OS: windows
3. api: v5.1.0

#### Steps to reproduce

  1. I have a site 123imot.bg, where I load the map and want to show the marker clusters. It used to work just fine, and it suddenly stopped on our live environment. It works ok in our dev and test environments. The only difference I can see is that we have google adsense script loading after the marker clusterer script, but the adsense injects scripts on top of the head. That is the only difference I see. The problem is there are no errors nothing, just the markers are not showing. The test env is working fine and is identical except the adsense scripts.

Any ideas how to resolve that or to troubleshoot?

**Comment by ltoshev** [comment]
Here is the test.123imot.bg working as expected:

![image](https://user-images.githubusercontent.com/1788597/120064536-4f5af600-c075-11eb-9e88-ff046b8f2bf1.png)

Her is the live one:

![image](https://user-images.githubusercontent.com/1788597/120064544-5bdf4e80-c075-11eb-8a93-fe1c8ecfef14.png)

**Comment by ltoshev** [comment]
Here is the live scripts loaded view:

![image](https://user-images.githubusercontent.com/1788597/120064565-7dd8d100-c075-11eb-8f15-d137dd1d4e62.png)

Here is the test env scripts loaded view:

![image](https://user-images.githubusercontent.com/1788597/120064580-8e894700-c075-11eb-9407-2fa0d58a916b.png)

**Comment by jpoehnelt** [comment]
I'm not sure how those scripts would conflict. Did you find any other differences?

**Comment by ltoshev** [comment]
Hi @jpoehnelt I have not found anything else. Any ideas where I can look at? The thing there are no errors in console is puzzling me. The code for init the clusters is definitely running. But why they dont show up? Is there a limit how much it can show?

**Comment by jpoehnelt** [comment]
I'm not sure where to start on this one. 🤔 Might be worth digging around in the debugger/inspector? The clusters should be in the dom tree.

**Comment by ltoshev** [comment]
I can confirm they are not in the DOM tree on the live env. And they are in the DOM tree on the test ENV.

Here is an image from test:

![image](https://user-images.githubusercontent.com/1788597/120445754-9c024200-c391-11eb-8fd8-bbfb2e5948ef.png)

Here is an image from live env:

![image](https://user-images.githubusercontent.com/1788597/120445834-afada880-c391-11eb-9bdc-ab260b0f8440.png)

**Comment by thexs-dev** [comment]
Do you have a live demo map (link) showing this behaviour, so we can have a closer look at this issue?

**Comment by ltoshev** [comment]
Hi, yes, the link for live is https://123imot.bg/, you need to login to see the map:

1. Go to https://123imot.bg/app/login -> in first box enter as username: ltoshev@vicesoft.com, second box pw: 88turnitOn+
2. After login go to this link to see the map: https://123imot.bg/app/tursene/imoti - this is the search properties page. There is a button to load the map called "Карта" click it and it will show you the map.
You will see no marker clusters are shown. 

Absolutely same code runs on https://test.123imot.bg, where the clusters do work:
1. Go to https://test.123imot.bg/app/login, use ltoshev@vicesoft.com and same PW as above
2. After login go to this link to see the map: https://test.123imot.bg/app/tursene/imoti - this is the search properties page. There is a button to load the map called "Карта" click it and it will show you the map.

You will see some marker clusters are shown and works as expected.

**Comment by thexs-dev** [comment]
I just did as suggested to open the live map and it worked as expected, including all markers and clusters you are missing
- see screenshot below, open the image to see the live URL in the address bar
- I am using Chrome in a Linux-Ubuntu computer
- I guess this won't help too much but at least you know it is working for others

![image](https://user-images.githubusercontent.com/11319351/120875447-e0e8cd00-c579-11eb-91f3-489fc3a51dde.png)

**Comment by ltoshev** [comment]
Hi, now its working on my end too. The difference is we deployed a new version yesterday where we bumped the marker clusterers script from 4.0.1 to 5.1.0 maybe that fixed it. I see there is a new package with new versioning here in the repo? How do we know when to upgrade and what will break if we do?

**Comment by ltoshev** [comment]
And today the markers are gone, we have not deployed any new version, I think its some network issue, could google is blocking requests or something from our map trying to use the service? Any suggestions on you end, could we have a version where it logs better how the clusters load? Could I turn this mode on to see what happens?

**Comment by jpoehnelt** [comment]
See #300.
