### ISSUE TITLE
Maps: Markers disappear while zooming

### ISSUE THREAD

**Issue by adnanhz** [googlemaps/js-markerclustererplus#221]
Hello, I am facing a problem with my app using this library. I noticed that the same problem happens in the Maps Javascript docs linked below, so I'll use that to demonstrate the issue.

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
2. OS type and version: macOS Big Sur V11.1
3. Library version and other environment information: none

#### Steps to reproduce

  1. Go to https://developers.google.com/maps/documentation/javascript/marker-clustering
  2. Under overview, in the map, click the "+" icon to zoom 
  3. During the zooming process, the clusters disappear and then they reappear after the zooming animation is complete. 
  
A better user experience would be to leave the markers visible as is the case in the native approach. 
Timestamped link to video demonstrating the native approach where the pins don't disappear abruptly but smoothly: https://youtu.be/FFm9NmSfjw0?list=PLOU2XLYxmsIKgVkdTcsULfTIIsKz4n-I8&t=107

How can we improve this?
Thanks!

**Comment by jpoehnelt** [comment]
See #300.
