### ISSUE TITLE
Number of marker on markercluster, not on default image

### ISSUE THREAD

**Issue by arno-st** [googlemaps/js-markerclustererplus#228]
On my googlemap, when I use makercluster.js from google, the number ar write correctly inside the image I take (m1 to m5).
but when using markerclusterplus it always outside.

here is the code:
		var clusterOptions = {
			ignoreHidden: true,
			zoomOnClick: true,
			imagePath:'./images/m',
			maxZoom: 15,
		}
		var markerCluster = new MarkerClusterer(map, markers, clusterOptions );

I join a file with the 2 images of how it is represented.
markerclusterplus:
		<script type="text/javascript" src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>

markercluster (it's all I got):
/**
 * @name MarkerClusterer for Google Maps v3
 * @version version 1.0
 * @author Luke Mahe
 * @fileoverview
 * The library creates and manages per-zoom-level clusters for large amounts of
 * markers.
 * <br/>
 * This is a v3 implementation of the
 * <a href="http://gmaps-utility-library-dev.googlecode.com/svn/tags/markerclusterer/"
 * >v2 MarkerClusterer</a>.
 */

**Comment by jpoehnelt** [comment]
See #300.
