### ISSUE TITLE
click event on top of the cluster

### ISSUE THREAD

**Issue by js08** [googlemaps/js-markerclustererplus#239]
Hi,

Can you let me know how to add an event when we click on the cluster. I tried using this line but not working.

google.maps.event.addListener(markerCluster, 'clusterclick', function(cluster)

Thanks,

**Comment by juzimmer** [comment]
While I looked into source code and found ..

`Note that the name of the "clusterclick" event has been deprecated. The new name is `click`, so please change your application code now.`


I still can't get it to work changing to click.

**Comment by juzimmer** [comment]
I actually just found out what my problem was and it was that I re-instantiated my global variable of `markerCluster = new MarkerClusterer` and forgot to re-register my event listeners on it. All works fine now.

`google.maps.event.addListener(markerCluster, "click", function (c) {
        console.log("click")
    });
    google.maps.event.addListener(markerCluster, "contextmenu", function (c) {
        console.log("contextmenu")
    });
    google.maps.event.addListener(markerCluster, "mouseover", function (c) {
        console.log("mouseover")
    });
    google.maps.event.addListener(markerCluster, "mouseout", function (c) {
        console.log("mouseout")
    });`
