### ISSUE TITLE
Large gridSize option issue

### ISSUE THREAD

**Issue by AaronMcCloskey** [googlemaps/js-markerclustererplus#246]
#### Environment details

1. MacOS Cataline v10.15.6
2. `"@googlemaps/markerclustererplus": "^1.2.0",`

#### Steps to reproduce

My map markers are `108px` wide, so I am using `108` for the `gridSize`.

However, this large `gridSize` seems to be causing issues, at the moment, it only appears when the map width & height is relatively small.

This [CodeSandbox](https://codesandbox.io/s/nervous-forest-459cq?file=/src/GoogleMap.js:1714-1756&resolutionWidth=411&resolutionHeight=500) shows the issue the best. It should open up in a responsive view, if it does not, open the view to be `411px x 500px`

There is a cluster that has `62` markers. Clicking on that cluster zooms in as expected, but the `62` marker cluster remains and clicking on that cluster does nothing?

If you set the window width to `450px` it works though? Or if you zoom in manually it works too. So I'm very confused. Is there anything I can do here, or is this simply out of my control?

Any help would be appreciated.

#### Code example

```
new MarkerClusterer(map, markers, {
  calculator: (gMarkers, numStyles) => {
    let index = 0;
    const count = gMarkers.length;
    let dv = count;
    while (dv !== 0) {
      dv = parseInt(dv / 10, 10);
      index += 1;
    }
    index = Math.min(index, numStyles);
    return {
      text: `${count} Points`,
      index
    };
  },
  gridSize: 108,
  styles: [
    {
      className: "clusterMarker",
      width: 108,
      height: 18
    }
  ]
});
```

**Comment by eggars** [comment]
same here! +1

**Comment by jpoehnelt** [comment]
See #300.
