### ISSUE TITLE
MarkerClusterer: Clusters appear above "use ctrl+scroll to zoom the map"

### ISSUE THREAD

**Issue by Mark-Hetherington** [googlemaps/js-markerclustererplus#256]
Using markerclustererplus v1.2.0, and a map with cooperative gestures, the clusters appear on top of the hint  "use ctrl+scroll to zoom the map"

#### Code example
See [codepen](https://codepen.io/mark_keo/pen/GRmyObb)

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by jpoehnelt** [comment]
See #300.
