### ISSUE TITLE
Multiple markers with same geolocation

### ISSUE THREAD

**Issue by neo1992** [googlemaps/js-markerclustererplus#261]
When I have 2 (or more) locations with the exact same geolocation (e.g. because they're in the same building), the cluster cannot be expanded:
![image](https://user-images.githubusercontent.com/7127039/129476760-6bc0c226-4da4-4c29-a805-9f46eb5c1b95.png)
There is currently no support for showing these markers and allow a clickthrough, this is very confusing.

There are a few 3rd party attempts to solve this: https://stackoverflow.com/questions/3548920/google-maps-api-v3-multiple-markers-on-exact-same-spot
But those require extra libraries, having to add custom code (making the upgrade process of js-markerclustererplus more cumbersome).

This should really just be an option in this library where we can specify how same geolocations should be handled, e.g.
1. move the same geolocation a few meters so the markers are shows distinctly.
2. add a new UI element where the markers are show in some sort of list and indicate they point to the same geolocation

**Comment by jpoehnelt** [comment]
See #300.
