### ISSUE TITLE
Overlaying markers over the cluster

### ISSUE THREAD

**Issue by lukeinage** [googlemaps/js-markerclustererplus#270]
In my project I have multiple placemarker types, one of those placemarker types is clustered and another isn't.
I would like to overlay my unclustered placemarkers over the cluster icon as they hold more important information than the cluster.

I see this is not currently possible as cluster icons are added to the overlayMouseTarget

this.getPanes().overlayMouseTarget.appendChild(this.div_);

Is there any workaround I can do?

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by jpoehnelt** [comment]
See #300.
