### ISSUE TITLE
Granular Multiple Identical Lng/Lat Marker Support

### ISSUE THREAD

**Issue by cuahsimarko** [googlemaps/js-markerclustererplus#31]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

 **Is your feature request related to a problem? Please describe.**
When multiple markers have identical lng/lat coordinates, a cluster is created. The expected behavior of clicking on a cluster and viewing markers no longer occurs. In our case, this breaks the experience of being able to click on a single marker for an additional info window.

 **Describe the solution you'd like**
One possible solution is to have markers splay out in a ring or otherwise be randomized into discrete markers on hover or click.

 **Describe alternatives you've considered**
Alternative could be to have the cluster convert to a marker, when clicked and any native Info window information from the google API would be consolidated and newline separated in that single marker

**Comment by filippiR** [comment]
hi, I am not part of the development team, but I went through this problem. To solve I set the maxzoom the code was like this
```
  new MarkerClusterer (map, markers, {
                     averageCenter: true,
                     imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
                     maxZoom: 20
                 });
```

**Comment by jpoehnelt** [comment]
See #300.
