### ISSUE TITLE
Zoom in only as far as is necessary to un-cluster?

### ISSUE THREAD

**Issue by dylantuohy** [googlemaps/js-markerclustererplus#48]
Hello, I have a question about some behaviour seen in the [Simple Example](https://googlemaps.github.io/js-markerclustererplus/examples/simple_example.html).

When clicking a cluster, the map zooms in and the markers become un-clustered. I can then zoom back out several times before those markers become re-clustered.

![new](https://user-images.githubusercontent.com/757918/98428957-eb89c500-2071-11eb-84a8-49b9cb2a9f07.gif)

Is it easily possible to zoom in only as far as is necessary to un-cluster the clicked cluster? So then, a single "zoom out" would cause them to re-cluster?

I am aware of the `maxZoom` property but I don't think that's actually what I'm looking for.

Thank you!

**Comment by jpoehnelt** [comment]
See #300.
