### ISSUE TITLE
Issues with clustering markers and pinch zoom on mobile

### ISSUE THREAD

**Issue by flojon** [googlemaps/js-markerclustererplus#76]
Hi, 

We have noticed a problem with clustering markers in our app. But we saw that the same problem happens with the example map at: 
https://developers.google.com/maps/documentation/javascript/marker-clustering 

First issue: 
If you put one finger on one clustering marker and another finger on another clustering marker and then pinch to zom in. After a short while the zoom will stop and all the clustering markers will dissapear. They show up again if you pan or adjust the zoom. 

Second issue: 
Sometimes when we try to pinch to zoom and happen to put one finger on a clustering marker the map will zoom out completly to the world map. We haven't figured out completly what triggers it. If it's certain spot on the clustering marker. But it will happen maybee 1 time in 10 tries... 

Both issues can happen on both iOS and Android. 

In our application we have a lot of clustering markers so the problem happens more frequently.

**Comment by jpoehnelt** [comment]
What's the function difference between the fork and the @googlemaps/markerclusterer-plus for pinch zoom?

**Comment by jpoehnelt** [comment]
https://github.com/googlemaps/js-markerclustererplus/blob/906ffead1c62cf71002219555fc1f174062d232a/src/cluster-icon.ts#L212 seems like a good starting point to debugging this.

**Comment by jeanmatthieud** [comment]
> Sorry I didn't get around to opening a PR for this, and now I'm totally out of the loop in what the original problem was (I've switched jobs multiple times since then, pandemic for you). @jeanmatthieud It's not ideal, but the workaround I posted seems to have worked for at least one other person. Maybe you could check the gist I posted? It seems there hasn't been any changes to the core lib so you could replace the package version in it's entirety with the version I posted. You could look into [patch package](https://www.npmjs.com/package/patch-package) to make it easier?

I didn't tried the patch. Sadly, the project I'm working on is not big enough to let me work more on this subject.

**Comment by jeanmatthieud** [comment]
> I'm having this same issue with the latest version too with the https://github.com/googlemaps/js-markerclustererplus Everything works fine on desktop. In the mobile, if you pinch zoom by **not** touching the cluster-icons, it works, but if you pinch zoom over marker icon, depending on the meta viewport settings, it either zooms the whole viewport or does not zoom at all.

I have the same behavior. I found somewhere that adding this CSS code on the cluster icon class disables the click (sadly) but also workaround the issue:
```css
pointer-events: none !important;
```

It's **not** a real fix (as the click on the cluster doesn't work anymore), but it's better that the zooming issue I have on mobile.

**Comment by jhappone** [comment]
> I have the same behavior. I found [somewhere](https://github.com/googlemaps/js-markerclustererplus/issues/10) that adding this CSS code on the cluster icon class disables the click (sadly) but also workaround the issue:
> 
> ```css
> pointer-events: none !important;
> ```
> 
> It's **not** a real fix (as the click on the cluster doesn't work anymore), but it's better that the zooming issue I have on mobile.

Unfortunately I cannot use this, but I'll try to enable it only on mobile and test how it works.

**Comment by TarasZakus** [comment]
Try this:
```
// TODO: remove, once this [this](https://github.com/googlemaps/js-markerclustererplus/issues/10) is resolved
google.maps.version = '3.31.9';

const markerCluster = new MarkerClusterer(map, markers);
```

**Comment by jpoehnelt** [comment]
See #300.
