### ISSUE TITLE
Add spider/spiderify for cluster

### ISSUE THREAD

**Issue by strarsis** [googlemaps/js-markerclustererplus#8]
Another way for showing clustered markers is to spiderify them:
https://github.com/jawj/OverlappingMarkerSpiderfier

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer. This allows for more custom rendering of cluster icons.

**Comment by dougwaldron** [comment]
@jpoehnelt How does the new version handle two markers with identical geocoordinates? (Or coordinates so close that they're indistinguishable at the greatest zoom level.) Would a separate "spiderfier" library still be needed?

**Comment by jpoehnelt** [comment]
It does not handle that case specifically, but it can be adapted with a custom renderer. Basically, a `render` function is called on each cluster and expects a google.maps.Marker to be returned, however this could potentially be modified to return multiple markers or other elements. I am open to supporting a wider interface for the return value of the render function.

https://github.com/googlemaps/js-markerclusterer/issues/9

**Comment by dougwaldron** [comment]
Thanks. That sounds reasonable, but I'm not a strong JavaScript programmer so I hope someone else with the same use case can weigh in eventually.
