### ISSUE TITLE
MarkerClusterer icon width / height is cutting the image

### ISSUE THREAD

**Issue by maalej** [googlemaps/js-markerclustererplus#9]
hi,
Specifying the icon width and height is cutting the icon instead of reducing / expanding its original size.
Am I missing something?

#### Environment details
MarkerClusterer version v3

#### Code example
https://jsfiddle.net/ty02p8vr/

**Comment by jpoehnelt** [comment]
It might be worth considering the recently refactored version of this library now found at https://github.com/googlemaps/js-markerclusterer.

**Comment by jpoehnelt** [comment]
See #300.
